### ISSUE TITLE
The new unified train_lm.py breaks custom configuration through arguments

### ISSUE THREAD

**Issue by Ivan-Zhou** [stanford-crfm/levanter#214] opened 2023-06-21 04:23 UTC
It seems the new unified train_lm.py treats `--model` as str; as a result, I can no longer set custom model configuration through arguments:

```
train_lm.py: error: unrecognized arguments: --model.gpt2.seq_len 512
usage: train_lm.py [-h] [--config_path str] [--model str]
                   [--initialize_from_hf str] [--use_hf_model_config str]
                   [--fcm_prob str] [--hf_save_path str] [--hf_upload str]
                   [--hf_save_steps str] [--data.id str] [--data.name str]
                   [--data.stream str] [--data.train_urls str]
                   [--data.validation_urls str] [--data.tokenizer str]
                   [--data.text_key str] [--data.cache_dir str]
                   [--data.enforce_eos str] [--data.splits str]
                   [--data.rows_per_chunk str] [--trainer.seed str]
                   [--trainer.log_dir str] [--trainer.run_base_dir str]
                   [--trainer.batch_axis str] [--trainer.fsdp_axis str]
                   [--trainer.tensor_parallel_axes str]
                   [--trainer.axis_resources str]
                   [--trainer.parameter_axis_resources str]
                   [--trainer.model_axis_size str]
                   [--trainer.train_batch_size str]
                   [--trainer.per_device_parallelism str]
                   [--trainer.per_device_eval_parallelism str]
                   [--trainer.num_train_steps str]
                   [--trainer.steps_per_eval str]
                   [--trainer.max_eval_batches str]
                   [--trainer.load_checkpoint str]
                   [--trainer.load_checkpoint_path str]
                   [--trainer.jax_config str]
                   [--trainer.require_accelerator str]
                   [--trainer.shutdown_at_exit str]
                   [--trainer.mp.param_dtype str]
                   [--trainer.mp.compute_dtype str]
                   [--trainer.mp.output_dtype str]
                   [--trainer.wandb.entity str] [--trainer.wandb.project str]
                   [--trainer.wandb.name str] [--trainer.wandb.tags str]
                   [--trainer.wandb.id str] [--trainer.wandb.group str]
                   [--trainer.wandb.mode str] [--trainer.wandb.resume str]
                   [--trainer.wandb.save_code str]
                   [--trainer.wandb.save_xla_dumps str]
                   [--trainer.checkpointer.base_path str]
                   [--trainer.checkpointer.save_interval str]
                   [--trainer.checkpointer.keep str]
                   [--trainer.distributed.coordinator_address str]
                   [--trainer.distributed.num_processes str]
                   [--trainer.distributed.process_id str]
                   [--trainer.distributed.local_device_ids str]
                   [--trainer.ray.address str]
                   [--trainer.ray.start_workers str]
                   [--trainer.ray.auto_start_cluster str]
                   [--optimizer.learning_rate str]
                   [--optimizer.weight_decay str] [--optimizer.beta1 str]
                   [--optimizer.beta2 str] [--optimizer.epsilon str]
                   [--optimizer.max_grad_norm str]
                   [--optimizer.min_lr_ratio str]
                   [--optimizer.warmup_ratio str]
                   [--optimizer.lr_schedule str]
train_lm.py: error: unrecognized arguments: --model.gpt2.seq_len 512
```

**Comment by dlwh** [comment] 2023-06-21 06:27
dupe of #207 i'm sorry i broke it. You have to do it in the yaml right now.

**Closed by dlwh** 2023-06-21 06:27 UTC

**Comment by Ivan-Zhou** [comment] 2023-06-21 17:01
No problem! Glad it is captured already.

**Comment by dlwh** [comment] 2023-06-21 17:06
I'll try to fix it today. I can't really fix it with the current config library, and they just told me they won't accept the necessary change to upstream it. There's an alternative library called simple-parsing (which is ironically much more complex) that can maybe handle it
