### ISSUE TITLE
Add Mixtral support

### ISSUE THREAD

**Issue by sr5434** [stanford-crfm/levanter#528] opened 2024-03-16 01:13 UTC
Could Mixtral be implemented? Thanks for any help you can provide.

**Comment by dlwh** [comment] 2024-03-16 01:24
There's a PR open at #483 but it's on pause for right now.. It's a bit tricky to implement MoE efficiently on TPU.

We're definitely interested!

**Comment by dlwh** [comment] 2024-03-16 01:24
closing as dupe of #473 #483

**Closed by dlwh** 2024-03-16 01:24 UTC

**Comment by sr5434** [comment] 2024-03-16 11:24
Mb
